# Generated by Django 4.0.2 on 2022-02-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='zip',
            field=models.IntegerField(max_length=10),
        ),
    ]
